
     [build]
       publish = "frontend"
       functions = "frontend/functions"

     [[redirects]]
       from = "/api/*"
       to = "/.netlify/functions/:splat"
       status = 200
       force = true
